// Mocks generated by Mockito 5.0.7 from annotations
// in flutter_simple_list/test/widget_test.dart.
// Do not manually edit this file.

import 'package:flutter_package_list/domain/GetAccountUseCase.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

// ignore_for_file: prefer_const_constructors

// ignore_for_file: avoid_redundant_argument_values

/// A class which mocks [GetAccountUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAccountUseCase extends _i1.Mock implements _i2.GetAccountUseCase {
  MockGetAccountUseCase() {
    _i1.throwOnMissingStub(this);
  }
}
